name: conversation_log
description: Store your Messages with ChatGPT
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  bot_toast: ^4.0.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_platform_alert: ^0.3.0
  flutter_prism: ^0.2.2
  flutter_window_close: ^0.2.2
  get_it: ^7.2.0
  intl: ^0.17.0
#  markdown_editor_plus: ^0.2.13
  markdown_toolbar: ^0.4.0
  markdown_viewer: ^0.5.0
  markdown_widget: ^2.0.0+1
  menu_bar: ^0.4.0
  menubar:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/menubar
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  window_manager: ^0.3.1

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
