name: conversation_log
description: Store your Messages with ChatGPT
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
#  flutter_markdown: ^0.7.4
#  markdown_editor_plus: ^0.2.13
#  markdown: ^7.2.1
#  markdown_viewer: ^0.5.0
#  markdown_widget: ^2.0.0+1
  menubar:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/menubar
  file_picker: ^10.2.2
  shared_preferences: ^2.5.3
  flutter_platform_alert: ^0.8.0
  flutter_prism: ^0.2.2
  flutter_window_close: ^1.3.0
  get_it: ^8.2.0
  bot_toast: ^4.1.3
  collection: ^1.19.1
  dartz: ^0.10.1
  desktop_drop: ^0.6.1
  equatable: ^2.0.7
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  lottie: ^3.3.1
  markdown_toolbar: ^0.5.0
  menu_bar: ^0.5.3
  provider: ^6.1.5
  search_highlight_text: ^1.0.0+2
  window_manager: ^0.5.1
  markdown_widget: ^2.3.2+6
  flutter_math_fork: ^0.7.4
  markdown: ^7.3.0
  flutter_widget_from_html_core: ^0.17.0
  html: ^0.15.6

dependency_overrides:
  archive: ^3.6.1

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/lottie/
